name: Acceptance Tests
on: [push,pull_request]

jobs:
  acceptance:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
        id: go

      - name: Check out code repository source code
        uses: actions/checkout@v2

      - name: Start icinga2
        run: make docker_start; sleep 30

      - name: Run acceptance tests
        run: make testacc
